kind: pipeline
name: default
steps:
  - name: docker
    image: plugins/docker
    settings:
      username: vesuviusua
      password:
        from_secret: docker_pass
      repo: vesuviusua/tg-bot
      tags:
        - latest
        - main