kind: pipeline
name: default
load: secrets
steps:
  - name: docker
    image: plugins/docker
    settings:
      username: vesuviusua
      password:
        from_secret: docker_pass
      repo: vesuviusua/tg-bot
      tags:
        - latest
  - name: deploy
    image: vesuviusua/tg-bot
    settings:
      host:
        from_secret: droplet_host
      username:
        from_secret: droplet_username
      key:
        from_secret: ssh_private_key
      target: /root/projects/tg-bot
      script:
        - docker login -u vesuviusua -p $DOCKER_PASS
        - docker-compose down
        - docker-compose pull
        - docker-compose up -d