kind: pipeline
name: default

steps:
  - name: docker
    image: plugins/docker
    settings:
      username: vesuviusua
      password:
        from_secret: docker_pass
      repo: vesuviusua/tg-bot
      tags:
        - latest
  - name: deploy
    image: appleboy/drone-ssh
    settings:
      host: 64.225.102.134
      username: root
      key:
        from_secret: ssh_private_key
      script:
        - set -e
        - cd /root/projects/tg-bot
        - docker-compose down
        - docker-compose pull
        - docker-compose up -d